import { z } from "zod";
import { PlanCategory, PlanStatus, PlanBillingCycle } from "./plan.types";

export const createPlanSchema = z.object({
  body: z.object({
    planName: z.string().min(3).max(100),
    planCode: z.string().min(2).max(50),
    description: z.string().optional(),
    category: z.nativeEnum(PlanCategory),
    status: z.nativeEnum(PlanStatus).optional(),
    billingCycle: z.array(z.nativeEnum(PlanBillingCycle)).optional(),
    pricing: z.object({
      monthlyPrice: z.number().min(0),
      quarterlyPrice: z.number().min(0).optional(),
      halfYearlyPrice: z.number().min(0).optional(),
      yearlyPrice: z.number().min(0),
      currency: z.string().default("INR"),
      taxPercent: z.number().min(0).max(100).optional(),
      discountPercent: z.number().min(0).max(100).optional(),
      razorpayPlanIdMonthly: z.string().optional(),
      razorpayPlanIdYearly: z.string().optional(),
    }),
    usageLimits: z.object({

      maxCenters: z.number().min(0),
      maxEmployees: z.number().min(0),
      maxCandidates: z.number().min(0),
      maxSubjects: z.number().min(0).optional(),
      maxExams: z.number().min(0),
      maxPapers: z.number().min(0).optional(),
      maxQuestionBankSize: z.number().min(0).optional(),
      storageLimitGB: z.number().min(0).optional(),
      apiRequestsPerMonth: z.number().min(0).optional(),
      maxManagers: z.number().min(0).optional(),
      maxConcurrentExams: z.number().min(0).optional(),
      maxActiveShifts: z.number().min(0).optional(),
      maxExamRooms: z.number().min(0).optional(),
      maxInvigilators: z.number().min(0).optional(),
      maxObservers: z.number().min(0).optional(),
      maxAiProctorSessions: z.number().min(0).optional(),
      maxFileUploadSizeMB: z.number().min(0).optional(),
      backupRetentionDays: z.number().min(0).optional(),
      auditLogRetentionDays: z.number().min(0).optional(),
      reportRetentionDays: z.number().min(0).optional(),
      sessionTimeoutMinutes: z.number().min(0).optional(),
      maxLoginDevices: z.number().min(0).optional(),
    }),
    features: z.object({
      questionBank: z.boolean().default(false),
      paperApproval: z.boolean().default(false),
      liveMonitoring: z.boolean().default(false),
      geoMonitoring: z.boolean().default(false),
      biometric: z.boolean().default(false),
      attendance: z.boolean().default(false),
      resultApproval: z.boolean().default(false),
      meritList: z.boolean().default(false),
      certificate: z.boolean().default(false),
      notifications: z.boolean().default(false),
      reports: z.boolean().default(false),
      apiAccess: z.boolean().default(false),
      fileStorage: z.boolean().default(false),
      importExport: z.boolean().default(false),
      customBranding: z.boolean().default(false),
      sso: z.boolean().default(false),
      auditLogs: z.boolean().default(false),
      offlineOMR: z.boolean().default(false),
      observerModule: z.boolean().default(false),
      nlpEvaluation: z.boolean().default(false),
      recruitingBodyModule: z.boolean().default(false),
      onlineExam: z.boolean().default(false),
      hybridExam: z.boolean().default(false),
      basicAiProctoring: z.boolean().default(false),
      fullAiProctoring: z.boolean().default(false),
      sixteenAiModules: z.boolean().default(false),
      cameraSnapshot: z.boolean().default(false),
      liveCameraStream: z.boolean().default(false),
      liveCameraAndVideo: z.boolean().default(false),
      gpsAtLogin: z.boolean().default(false),
      continuousGpsAndGeoFence: z.boolean().default(false),
      fullGpsAndAiGeoFraud: z.boolean().default(false),
      hallTicketAndSeating: z.boolean().default(false),
      recruitingBodyDetailsOnHallTicket: z.boolean().default(false),
      recruitingBodyPortalLogin: z.boolean().default(false),
      whiteLabelAndCustomDomain: z.boolean().default(false),
      dedicatedServerAndSla: z.boolean().default(false),
      omrStrongRoomBell: z.boolean().default(false),
      faceVerification: z.boolean().default(false),
      browserLock: z.boolean().default(false),
      safeExamBrowser: z.boolean().default(false),
      deviceTrust: z.boolean().default(false),
      screenRecording: z.boolean().default(false),
      clipboardBlocking: z.boolean().default(false),
      voiceDetection: z.boolean().default(false),
      activityLogs: z.boolean().default(false),
      analyticsDashboard: z.boolean().default(false),
      scheduledReports: z.boolean().default(false),
      customReports: z.boolean().default(false),
      webhooks: z.boolean().default(false),
      apiRateLimiting: z.boolean().default(false),
      whiteLabel: z.boolean().default(false),
      whiteLabelLogin: z.boolean().default(false),
      customDomain: z.boolean().default(false),
      darkTheme: z.boolean().default(false),
      customTheme: z.boolean().default(false),
      smtpConfiguration: z.boolean().default(false),
      emailTemplates: z.boolean().default(false),
      certificateTemplates: z.boolean().default(false),
      admitCardTemplates: z.boolean().default(false),
      twoFactorAuth: z.boolean().default(false),
      ldapActiveDirectory: z.boolean().default(false),
      ipWhitelisting: z.boolean().default(false),
      recruitingModule: z.boolean().default(false),
      paymentGateway: z.boolean().default(false),
      subscription: z.boolean().default(false),
      invoices: z.boolean().default(false),
      autoInvoice: z.boolean().default(false),
    }),
  }),
});

export const updatePlanSchema = z.object({
  body: createPlanSchema.shape.body.partial(),
});

export const queryPlanSchema = z.object({
  query: z.object({
    page: z.string().optional(),
    limit: z.string().optional(),
    search: z.string().optional(),
    status: z.nativeEnum(PlanStatus).optional(),
    category: z.nativeEnum(PlanCategory).optional(),
    sortBy: z.string().optional(),
    sortOrder: z.enum(["asc", "desc"]).optional(),
  }),
});
