import { Schema, model } from "mongoose";
import { IPlan, PlanBillingCycle, PlanCategory, PlanStatus } from "./plan.types";

const PlanSchema = new Schema<IPlan>(
  {
    planName: { type: String, required: true, trim: true },
    planCode: { type: String, required: true, uppercase: true, trim: true },
    description: { type: String, trim: true },
    category: {
      type: String,
      enum: Object.values(PlanCategory),
      default: PlanCategory.PRIVATE,
    },
    status: {
      type: String,
      enum: Object.values(PlanStatus),
      default: PlanStatus.INACTIVE,
    },
    billingCycle: [
      {
        type: String,
        enum: Object.values(PlanBillingCycle),
      },
    ],
    pricing: {
      monthlyPrice: { type: Number, default: 0 },
      quarterlyPrice: { type: Number, default: 0 },
      halfYearlyPrice: { type: Number, default: 0 },
      yearlyPrice: { type: Number, default: 0 },
      currency: { type: String, default: "INR" },
      taxPercent: { type: Number, default: 0 },
      discountPercent: { type: Number, default: 0 },
      razorpayPlanIdMonthly: { type: String },
      razorpayPlanIdYearly: { type: String },
    },
    usageLimits: {
      maxBranches: { type: Number, default: 0 },
      maxCenters: { type: Number, default: 0 },
      maxEmployees: { type: Number, default: 0 },
      maxCandidates: { type: Number, default: 0 },
      maxSubjects: { type: Number, default: 0 },
      maxExams: { type: Number, default: 0 },
      maxPapers: { type: Number, default: 0 },
      maxQuestionBankSize: { type: Number, default: 0 },
      storageLimitGB: { type: Number, default: 0 },
      apiRequestsPerMonth: { type: Number, default: 0 },
      maxManagers: { type: Number, default: 0 },
      maxConcurrentExams: { type: Number, default: 0 },
      maxActiveShifts: { type: Number, default: 0 },
      maxExamRooms: { type: Number, default: 0 },
      maxInvigilators: { type: Number, default: 0 },
      maxObservers: { type: Number, default: 0 },
      maxAiProctorSessions: { type: Number, default: 0 },
      maxFileUploadSizeMB: { type: Number, default: 0 },
      backupRetentionDays: { type: Number, default: 0 },
      auditLogRetentionDays: { type: Number, default: 0 },
      reportRetentionDays: { type: Number, default: 0 },
      sessionTimeoutMinutes: { type: Number, default: 0 },
      maxLoginDevices: { type: Number, default: 0 },
    },
    features: {
      questionBank: { type: Boolean, default: false },
      paperApproval: { type: Boolean, default: false },
      liveMonitoring: { type: Boolean, default: false },
      geoMonitoring: { type: Boolean, default: false },
      biometric: { type: Boolean, default: false },
      attendance: { type: Boolean, default: false },
      resultApproval: { type: Boolean, default: false },
      meritList: { type: Boolean, default: false },
      certificate: { type: Boolean, default: false },
      notifications: { type: Boolean, default: false },
      reports: { type: Boolean, default: false },
      apiAccess: { type: Boolean, default: false },
      fileStorage: { type: Boolean, default: false },
      importExport: { type: Boolean, default: false },
      customBranding: { type: Boolean, default: false },
      sso: { type: Boolean, default: false },
      auditLogs: { type: Boolean, default: false },
      offlineOMR: { type: Boolean, default: false },
      observerModule: { type: Boolean, default: false },
      nlpEvaluation: { type: Boolean, default: false },
      recruitingBodyModule: { type: Boolean, default: false },
      onlineExam: { type: Boolean, default: false },
      hybridExam: { type: Boolean, default: false },
      basicAiProctoring: { type: Boolean, default: false },
      fullAiProctoring: { type: Boolean, default: false },
      sixteenAiModules: { type: Boolean, default: false },
      cameraSnapshot: { type: Boolean, default: false },
      liveCameraStream: { type: Boolean, default: false },
      liveCameraAndVideo: { type: Boolean, default: false },
      gpsAtLogin: { type: Boolean, default: false },
      continuousGpsAndGeoFence: { type: Boolean, default: false },
      fullGpsAndAiGeoFraud: { type: Boolean, default: false },
      hallTicketAndSeating: { type: Boolean, default: false },
      recruitingBodyDetailsOnHallTicket: { type: Boolean, default: false },
      recruitingBodyPortalLogin: { type: Boolean, default: false },
      whiteLabelAndCustomDomain: { type: Boolean, default: false },
      dedicatedServerAndSla: { type: Boolean, default: false },
      omrStrongRoomBell: { type: Boolean, default: false },
      faceVerification: { type: Boolean, default: false },
      browserLock: { type: Boolean, default: false },
      safeExamBrowser: { type: Boolean, default: false },
      deviceTrust: { type: Boolean, default: false },
      screenRecording: { type: Boolean, default: false },
      clipboardBlocking: { type: Boolean, default: false },
      voiceDetection: { type: Boolean, default: false },
      activityLogs: { type: Boolean, default: false },
      analyticsDashboard: { type: Boolean, default: false },
      scheduledReports: { type: Boolean, default: false },
      customReports: { type: Boolean, default: false },
      webhooks: { type: Boolean, default: false },
      apiRateLimiting: { type: Boolean, default: false },
      whiteLabel: { type: Boolean, default: false },
      whiteLabelLogin: { type: Boolean, default: false },
      customDomain: { type: Boolean, default: false },
      darkTheme: { type: Boolean, default: false },
      customTheme: { type: Boolean, default: false },
      smtpConfiguration: { type: Boolean, default: false },
      emailTemplates: { type: Boolean, default: false },
      certificateTemplates: { type: Boolean, default: false },
      admitCardTemplates: { type: Boolean, default: false },
      twoFactorAuth: { type: Boolean, default: false },
      ldapActiveDirectory: { type: Boolean, default: false },
      ipWhitelisting: { type: Boolean, default: false },
      recruitingModule: { type: Boolean, default: false },
      paymentGateway: { type: Boolean, default: false },
      subscription: { type: Boolean, default: false },
      invoices: { type: Boolean, default: false },
      autoInvoice: { type: Boolean, default: false },
    },
    activeCompaniesCount: { type: Number, default: 0 },
    createdBy: { type: Schema.Types.ObjectId, ref: "User", required: true },
    updatedBy: { type: Schema.Types.ObjectId, ref: "User" },
    isDeleted: { type: Boolean, default: false },
  },
  {
    timestamps: true,
  }
);

PlanSchema.index({ planCode: 1 }, { unique: true, partialFilterExpression: { isDeleted: false } });
PlanSchema.index({ status: 1 });
PlanSchema.index({ category: 1 });
PlanSchema.index({ "pricing.monthlyPrice": 1 });

const Plan = model<IPlan>("Plan", PlanSchema);
export default Plan;
