import type { Paper, PaperQuestion } from '../types';

export const DUMMY_QUESTIONS: PaperQuestion[] = [
  { id: 'q1', text: 'What is the capital of France?', type: 'MCQ', difficulty: 'Easy', marks: 1, topic: 'Geography' },
  { id: 'q2', text: 'Explain the theory of relativity.', type: 'Descriptive', difficulty: 'Hard', marks: 5, topic: 'Physics' },
  { id: 'q3', text: 'Water boils at 100 degrees Celsius.', type: 'True/False', difficulty: 'Easy', marks: 1, topic: 'Science' },
  { id: 'q4', text: 'Select all prime numbers.', type: 'MSQ', difficulty: 'Medium', marks: 2, topic: 'Mathematics' },
  { id: 'q5', text: 'Who wrote Hamlet?', type: 'MCQ', difficulty: 'Medium', marks: 1, topic: 'Literature' },
  { id: 'q6', text: 'Describe the process of photosynthesis.', type: 'Descriptive', difficulty: 'Medium', marks: 3, topic: 'Biology' },
  { id: 'q7', text: 'The Great Wall of China is visible from space.', type: 'True/False', difficulty: 'Easy', marks: 1, topic: 'History' },
  { id: 'q8', text: 'Which of the following are mammals?', type: 'MSQ', difficulty: 'Easy', marks: 2, topic: 'Biology' },
];

export const DUMMY_PAPERS: Paper[] = [
  {
    id: '1',
    name: 'Midterm Science Exam',
    code: 'SCI101',
    subject: 'Science',
    examType: 'Midterm',
    language: 'English',
    duration: 120,
    passingMarks: 40,
    totalMarks: 50,
    negativeMarking: false,
    status: 'Published',
    approvalStatus: 'Approved',
    createdBy: 'John Doe',
    createdAt: '2026-07-01T10:00:00Z',
    updatedAt: '2026-07-05T14:30:00Z',
    blueprint: {
      easyQuestions: 10,
      mediumQuestions: 5,
      hardQuestions: 2,
      mcqCount: 10,
      msqCount: 2,
      tfCount: 3,
      descriptiveCount: 2,
    },
    questions: DUMMY_QUESTIONS.slice(0, 4),
  },
  {
    id: '2',
    name: 'Final Mathematics Exam',
    code: 'MATH202',
    subject: 'Mathematics',
    examType: 'Final',
    language: 'English',
    duration: 180,
    passingMarks: 35,
    totalMarks: 100,
    negativeMarking: true,
    status: 'Draft',
    approvalStatus: 'Pending',
    createdBy: 'Jane Smith',
    createdAt: '2026-07-10T09:15:00Z',
    blueprint: {
      easyQuestions: 5,
      mediumQuestions: 10,
      hardQuestions: 5,
      mcqCount: 10,
      msqCount: 5,
      tfCount: 0,
      descriptiveCount: 5,
    },
    questions: DUMMY_QUESTIONS.slice(2, 6),
  },
  {
    id: '3',
    name: 'History Quiz 1',
    code: 'HIS001',
    subject: 'History',
    examType: 'Quiz',
    language: 'English',
    duration: 30,
    passingMarks: 10,
    totalMarks: 75,
    negativeMarking: false,
    status: 'Archived',
    approvalStatus: 'Rejected',
    createdBy: 'Alice Johnson',
    createdAt: '2026-06-15T11:45:00Z',
    blueprint: {
      easyQuestions: 5,
      mediumQuestions: 5,
      hardQuestions: 0,
      mcqCount: 10,
      msqCount: 0,
      tfCount: 0,
      descriptiveCount: 0,
    },
    questions: [DUMMY_QUESTIONS[6]],
  },
];
