/**
 * Placeholder for Vite PWA Manifest Configuration
 * This would typically be generated by vite-plugin-pwa in vite.config.ts,
 * but this file serves as the configuration source of truth for UI components.
 */
export const manifestConfig = {
  name: 'Examguard Platform',
  shortName: 'Examguard',
  description: 'Enterprise Assessment & Examination Platform',
  themeColor: '#4f46e5',
  backgroundColor: '#f8fafc',
  display: 'standalone',
  orientation: 'portrait-primary',
};
