import type { Question } from '../types';

export const MOCK_QUESTIONS: Question[] = [
  {
    id: 'Q-1001',
    subject: 'Advanced Mathematics',
    topic: 'Calculus',
    chapter: 'Derivatives',
    questionType: 'Single Choice (MCQ)',
    difficulty: 'Medium',
    language: 'English',
    questionText: '<p>What is the derivative of <strong>f(x) = x^2</strong>?</p>',
    options: [
      { id: 'opt1', text: 'x', isCorrect: false, order: 1 },
      { id: 'opt2', text: '2x', isCorrect: true, order: 2 },
      { id: 'opt3', text: 'x^2', isCorrect: false, order: 3 },
      { id: 'opt4', text: '2', isCorrect: false, order: 4 },
    ],
    explanation: '<p>The power rule states that the derivative of x^n is n*x^(n-1). For x^2, this is 2x.</p>',
    marks: 4,
    negativeMarks: 1,
    timeLimitSeconds: 60,
    metadata: {
      keywords: ['calculus', 'derivative', 'power rule'],
      tags: ['Important', 'Previous Year'],
      bloomsLevel: 'Application',
      cognitiveLevel: 'Medium',
    },
    status: 'Approved',
    approvalStatus: 'Approved',
    createdBy: 'John Doe',
    createdAt: '2023-10-01T10:00:00Z',
    updatedAt: '2023-10-05T14:30:00Z',
  },
  {
    id: 'Q-1002',
    subject: 'Physics',
    topic: 'Mechanics',
    chapter: 'Newton\'s Laws',
    questionType: 'Multiple Choice (MSQ)',
    difficulty: 'Hard',
    language: 'English',
    questionText: '<p>Which of the following are consequences of Newton\'s Third Law?</p>',
    options: [
      { id: 'opt1', text: 'Recoil of a gun', isCorrect: true, order: 1 },
      { id: 'opt2', text: 'Swimming', isCorrect: true, order: 2 },
      { id: 'opt3', text: 'A book resting on a table', isCorrect: true, order: 3 },
      { id: 'opt4', text: 'A car turning a corner', isCorrect: false, order: 4 },
    ],
    explanation: '<p>Every action has an equal and opposite reaction.</p>',
    marks: 4,
    negativeMarks: 1,
    metadata: {
      keywords: ['newton', 'laws', 'reaction'],
      tags: [],
      bloomsLevel: 'Understanding',
      cognitiveLevel: 'High',
    },
    status: 'Pending Review',
    approvalStatus: 'Pending',
    createdBy: 'Jane Smith',
    createdAt: '2023-10-02T11:15:00Z',
    updatedAt: '2023-10-02T11:15:00Z',
  },
  {
    id: 'Q-1003',
    subject: 'Computer Science',
    topic: 'Data Structures',
    chapter: 'Trees',
    questionType: 'True / False',
    difficulty: 'Easy',
    language: 'English',
    questionText: '<p>A binary search tree guarantees O(log n) time complexity for search operations in all cases.</p>',
    options: [
      { id: 'opt1', text: 'True', isCorrect: false, order: 1 },
      { id: 'opt2', text: 'False', isCorrect: true, order: 2 },
    ],
    explanation: '<p>In the worst case (unbalanced tree), the time complexity is O(n).</p>',
    marks: 2,
    negativeMarks: 0.5,
    metadata: {
      keywords: ['bst', 'time complexity'],
      tags: ['Core'],
      bloomsLevel: 'Knowledge',
      cognitiveLevel: 'Low',
    },
    status: 'Draft',
    approvalStatus: 'Pending',
    createdBy: 'Alice Johnson',
    createdAt: '2023-10-10T09:00:00Z',
    updatedAt: '2023-10-10T09:00:00Z',
  },
  {
    id: 'Q-1004',
    subject: 'Chemistry',
    topic: 'Organic Chemistry',
    chapter: 'Alkanes',
    questionType: 'Descriptive',
    difficulty: 'Medium',
    language: 'English',
    questionText: '<p>Explain the process of halogenation of alkanes.</p>',
    options: [],
    explanation: '<p>Free radical substitution mechanism...</p>',
    marks: 10,
    negativeMarks: 0,
    metadata: {
      keywords: ['halogenation', 'alkanes'],
      tags: ['Subjective'],
      bloomsLevel: 'Analysis',
      cognitiveLevel: 'Medium',
    },
    status: 'Rejected',
    approvalStatus: 'Rejected',
    createdBy: 'Bob Brown',
    createdAt: '2023-09-15T08:00:00Z',
    updatedAt: '2023-09-20T10:00:00Z',
  }
];

export const MOCK_SUBJECTS = ['Advanced Mathematics', 'Physics', 'Chemistry', 'Computer Science', 'Biology'];
export const MOCK_TOPICS = ['Calculus', 'Algebra', 'Mechanics', 'Organic Chemistry', 'Data Structures', 'Cell Biology'];
export const MOCK_CHAPTERS = ['Derivatives', 'Integrals', 'Newton\'s Laws', 'Alkanes', 'Trees', 'Genetics'];
