import Report from "./report.model";
import { BaseRepository } from "../../common/base.repository";

class ReportRepository extends BaseRepository<any> {
  constructor() {
    super(Report, [
      "generatedBy",
      "companyId",
      "branchId",
      "centerId",
      "examId",
      "fileId"
    ]);
  }

  /*
    |--------------------------------------------------------------------------
    | Find By Generated By
    |--------------------------------------------------------------------------
    */

  async findByGeneratedBy(generatedBy: string) {
    return Report.find({
      generatedBy,
    }).sort({
      createdAt: -1,
    });
  }

  /*
    |--------------------------------------------------------------------------
    | Find By Company
    |--------------------------------------------------------------------------
    */

  async findByCompany(companyId: string) {
    return Report.find({
      companyId,
    }).sort({
      createdAt: -1,
    });
  }

  /*
    |--------------------------------------------------------------------------
    | Delete By Id
    |--------------------------------------------------------------------------
    */

  async deleteById(id: string) {
    return Report.findByIdAndDelete(id);
  }
}

export default new ReportRepository();
