import { z } from "zod";
import { PlanCategory, PlanStatus, PlanBillingCycle } from "../types/plan.types";

export const planSchema = z.object({
  planName: z.string().trim().min(3, "Plan name must be at least 3 characters").max(100),
  planCode: z.string().trim().min(2, "Plan code must be at least 2 characters").max(50),
  description: z.string().optional(),
  category: z.nativeEnum(PlanCategory),
  status: z.nativeEnum(PlanStatus).default(PlanStatus.INACTIVE),
  billingCycle: z.array(z.nativeEnum(PlanBillingCycle)).optional(),
  
  pricing: z.object({
    monthlyPrice: z.coerce.number().min(0),
    quarterlyPrice: z.coerce.number().min(0).default(0),
    halfYearlyPrice: z.coerce.number().min(0).default(0),
    yearlyPrice: z.coerce.number().min(0),
    currency: z.string().default("INR"),
    taxPercent: z.coerce.number().min(0).max(100).default(0),
    discountPercent: z.coerce.number().min(0).max(100).default(0),
    razorpayPlanIdMonthly: z.string().optional(),
    razorpayPlanIdYearly: z.string().optional(),
  }),
  
  usageLimits: z.object({
    maxCenters: z.coerce.number().min(0),
    maxEmployees: z.coerce.number().min(0),
    maxCandidates: z.coerce.number().min(0),
    maxSubjects: z.coerce.number().min(0).default(0),
    maxExams: z.coerce.number().min(0),
    maxPapers: z.coerce.number().min(0).default(0),
    maxQuestionBankSize: z.coerce.number().min(0).default(0),
    storageLimitGB: z.coerce.number().min(0).default(0),
    apiRequestsPerMonth: z.coerce.number().min(0).default(0),
    maxManagers: z.coerce.number().min(0).default(0),
    maxConcurrentExams: z.coerce.number().min(0).default(0),
    maxActiveShifts: z.coerce.number().min(0).default(0),
    maxExamRooms: z.coerce.number().min(0).default(0),
    maxInvigilators: z.coerce.number().min(0).default(0),
    maxObservers: z.coerce.number().min(0).default(0),
    maxAiProctorSessions: z.coerce.number().min(0).default(0),
    maxFileUploadSizeMB: z.coerce.number().min(0).default(0),
    backupRetentionDays: z.coerce.number().min(0).default(0),
    auditLogRetentionDays: z.coerce.number().min(0).default(0),
    reportRetentionDays: z.coerce.number().min(0).default(0),
    sessionTimeoutMinutes: z.coerce.number().min(0).default(0),
    maxLoginDevices: z.coerce.number().min(0).default(0),
  }),
  
  features: z.object({
    questionBank: z.boolean().default(false),
    paperApproval: z.boolean().default(false),
    liveMonitoring: z.boolean().default(false),
    geoMonitoring: z.boolean().default(false),
    biometric: z.boolean().default(false),
    attendance: z.boolean().default(false),
    resultApproval: z.boolean().default(false),
    meritList: z.boolean().default(false),
    certificate: z.boolean().default(false),
    notifications: z.boolean().default(false),
    reports: z.boolean().default(false),
    apiAccess: z.boolean().default(false),
    fileStorage: z.boolean().default(false),
    importExport: z.boolean().default(false),
    customBranding: z.boolean().default(false),
    sso: z.boolean().default(false),
    auditLogs: z.boolean().default(false),
    offlineOMR: z.boolean().default(false),
    observerModule: z.boolean().default(false),
    nlpEvaluation: z.boolean().default(false),
    recruitingBodyModule: z.boolean().default(false),
    onlineExam: z.boolean().default(false),
    hybridExam: z.boolean().default(false),
    basicAiProctoring: z.boolean().default(false),
    fullAiProctoring: z.boolean().default(false),
    sixteenAiModules: z.boolean().default(false),
    cameraSnapshot: z.boolean().default(false),
    liveCameraStream: z.boolean().default(false),
    liveCameraAndVideo: z.boolean().default(false),
    gpsAtLogin: z.boolean().default(false),
    continuousGpsAndGeoFence: z.boolean().default(false),
    fullGpsAndAiGeoFraud: z.boolean().default(false),
    hallTicketAndSeating: z.boolean().default(false),
    recruitingBodyDetailsOnHallTicket: z.boolean().default(false),
    recruitingBodyPortalLogin: z.boolean().default(false),
    whiteLabelAndCustomDomain: z.boolean().default(false),
    dedicatedServerAndSla: z.boolean().default(false),
    omrStrongRoomBell: z.boolean().default(false),
    faceVerification: z.boolean().default(false),
    browserLock: z.boolean().default(false),
    safeExamBrowser: z.boolean().default(false),
    deviceTrust: z.boolean().default(false),
    screenRecording: z.boolean().default(false),
    clipboardBlocking: z.boolean().default(false),
    voiceDetection: z.boolean().default(false),
    activityLogs: z.boolean().default(false),
    analyticsDashboard: z.boolean().default(false),
    scheduledReports: z.boolean().default(false),
    customReports: z.boolean().default(false),
    webhooks: z.boolean().default(false),
    apiRateLimiting: z.boolean().default(false),
    whiteLabel: z.boolean().default(false),
    whiteLabelLogin: z.boolean().default(false),
    customDomain: z.boolean().default(false),
    darkTheme: z.boolean().default(false),
    customTheme: z.boolean().default(false),
    smtpConfiguration: z.boolean().default(false),
    emailTemplates: z.boolean().default(false),
    certificateTemplates: z.boolean().default(false),
    admitCardTemplates: z.boolean().default(false),
    twoFactorAuth: z.boolean().default(false),
    ldapActiveDirectory: z.boolean().default(false),
    ipWhitelisting: z.boolean().default(false),
    recruitingModule: z.boolean().default(false),
    paymentGateway: z.boolean().default(false),
    subscription: z.boolean().default(false),
    invoices: z.boolean().default(false),
    autoInvoice: z.boolean().default(false),
  }),
});

export type PlanFormValues = z.infer<typeof planSchema>;
