import type { Subject } from '../types';

export const MOCK_SUBJECTS: Subject[] = [
  {
    id: '1',
    code: 'MATH-101',
    name: 'Advanced Mathematics',
    description: 'Calculus, Linear Algebra, and Differential Equations for engineering students.',
    examType: 'Multiple Choice',
    language: 'English',
    durationMinutes: 120,
    totalQuestions: 100,
    totalMarks: 100,
    passingMarks: 40,
    negativeMarking: true,
    negativeMarksPerQuestion: 0.25,
    displayOrder: 1,
    category: 'University',
    status: 'Active',
    createdBy: 'John Doe',
    createdAt: '2023-10-01T10:00:00Z',
    updatedAt: '2023-10-05T12:00:00Z'
  },
  {
    id: '2',
    code: 'PHYS-202',
    name: 'Quantum Physics',
    description: 'Introduction to quantum mechanics and particle physics.',
    examType: 'Subjective',
    language: 'English',
    durationMinutes: 180,
    totalQuestions: 10,
    totalMarks: 100,
    passingMarks: 50,
    negativeMarking: false,
    negativeMarksPerQuestion: 0,
    displayOrder: 2,
    category: 'University',
    status: 'Active',
    createdBy: 'Jane Smith',
    createdAt: '2023-10-02T10:00:00Z',
    updatedAt: '2023-10-02T10:00:00Z'
  },
  {
    id: '3',
    code: 'BANK-PO',
    name: 'Bank PO Quantitative Aptitude',
    description: 'Aptitude test for probationary officers recruitment.',
    examType: 'Multiple Choice',
    language: 'Hindi',
    durationMinutes: 60,
    totalQuestions: 50,
    totalMarks: 50,
    passingMarks: 25,
    negativeMarking: true,
    negativeMarksPerQuestion: 0.33,
    displayOrder: 3,
    category: 'Competitive',
    status: 'Active',
    createdBy: 'Admin User',
    createdAt: '2023-10-10T09:00:00Z',
    updatedAt: '2023-10-11T09:00:00Z'
  },
  {
    id: '4',
    code: 'AWS-SAA',
    name: 'AWS Solutions Architect Associate',
    description: 'Certification exam for cloud architecture on AWS.',
    examType: 'Multiple Choice',
    language: 'English',
    durationMinutes: 130,
    totalQuestions: 65,
    totalMarks: 1000,
    passingMarks: 720,
    negativeMarking: false,
    negativeMarksPerQuestion: 0,
    displayOrder: 4,
    category: 'Certification',
    status: 'Inactive',
    createdBy: 'System User',
    createdAt: '2023-09-15T08:00:00Z',
    updatedAt: '2023-09-15T08:00:00Z'
  }
];
