export enum UserRole {
  MASTER_ADMIN = "MASTER_ADMIN",

  COMPANY_ADMIN = "COMPANY_ADMIN",

  BRANCH_MANAGER = "BRANCH_MANAGER",

  CENTER_MANAGER = "CENTER_MANAGER",

  EXAM_MANAGER = "EXAM_MANAGER",

  PAPER_SETTER = "PAPER_SETTER",

  QUESTION_SETTER = "QUESTION_SETTER",

  BIOMETRIC_VERIFIER = "BIOMETRIC_VERIFIER",

  ENTRY_CHECKER = "ENTRY_CHECKER",

  OBSERVER = "OBSERVER",

  GOVT_AUTHORITY = "GOVT_AUTHORITY",

  TECHNICAL_MANAGER = "TECHNICAL_MANAGER",

  INVIGILATOR = "INVIGILATOR",

  CANDIDATE = "CANDIDATE",

  AI_PROCTOR = "AI_PROCTOR",

  COMMAND_CENTER = "COMMAND_CENTER",

  ADMIN = "ADMIN",

  STATE_MANAGER = "STATE_MANAGER",

  CITY_MANAGER = "CITY_MANAGER",
}
