import type { PaperApproval, ApprovalHistoryItem, ApprovalQuestion } from '../types';

export const DUMMY_PAPER_APPROVALS: PaperApproval[] = [
  {
    id: 'app-001',
    paperId: 'p-101',
    paperCode: 'PHY-101-2024',
    paperName: 'Physics Midterm 2024',
    subject: 'Physics',
    version: 'v1.2',
    reviewStatus: 'Completed',
    approvalStatus: 'Pending',
    priority: 'High',
    approver: 'Sarah Jenkins',
    createdDate: '2024-03-15T09:00:00Z',
  },
  {
    id: 'app-002',
    paperId: 'p-102',
    paperCode: 'MATH-201-2024',
    paperName: 'Advanced Calculus Final',
    subject: 'Mathematics',
    version: 'v2.0',
    reviewStatus: 'Completed',
    approvalStatus: 'In Review',
    priority: 'Critical',
    approver: 'Dr. Alan Math',
    createdDate: '2024-03-14T10:30:00Z',
  },
  {
    id: 'app-003',
    paperId: 'p-103',
    paperCode: 'CHEM-101-2024',
    paperName: 'Chemistry Basics',
    subject: 'Chemistry',
    version: 'v1.0',
    reviewStatus: 'Completed',
    approvalStatus: 'Approved',
    priority: 'Medium',
    approver: 'Dr. Emily Chem',
    createdDate: '2024-03-10T14:15:00Z',
  },
  {
    id: 'app-004',
    paperId: 'p-104',
    paperCode: 'CS-301-2024',
    paperName: 'Data Structures Midterm',
    subject: 'Computer Science',
    version: 'v1.1',
    reviewStatus: 'Completed',
    approvalStatus: 'Rejected',
    priority: 'High',
    approver: 'Prof. Turing',
    createdDate: '2024-03-12T11:45:00Z',
  },
];

export const DUMMY_APPROVAL_HISTORY: ApprovalHistoryItem[] = [
  {
    id: 'hist-001',
    paperId: 'p-101',
    approverName: 'System',
    action: 'Approval Started',
    remarks: 'Paper review completed, sent for final approval.',
    timestamp: '2024-03-15T09:00:00Z',
    version: 'v1.2',
  },
  {
    id: 'hist-002',
    paperId: 'p-102',
    approverName: 'System',
    action: 'Approval Started',
    remarks: 'Paper review completed.',
    timestamp: '2024-03-14T10:30:00Z',
    version: 'v2.0',
  },
  {
    id: 'hist-003',
    paperId: 'p-103',
    approverName: 'Dr. Emily Chem',
    action: 'Approved',
    remarks: 'All looks good. Approved for publishing.',
    timestamp: '2024-03-11T16:20:00Z',
    version: 'v1.0',
  },
  {
    id: 'hist-004',
    paperId: 'p-104',
    approverName: 'Prof. Turing',
    action: 'Rejected',
    remarks: 'Blueprint does not align with syllabus. Please revise heavily.',
    timestamp: '2024-03-13T09:15:00Z',
    version: 'v1.1',
  },
];

export const DUMMY_APPROVAL_QUESTIONS: ApprovalQuestion[] = [
  {
    id: 'q-001',
    text: 'What is the speed of light in a vacuum?',
    type: 'MCQ',
    difficulty: 'Easy',
    marks: 1,
    topic: 'Electromagnetism',
  },
  {
    id: 'q-002',
    text: 'Explain Newton\'s Second Law of Motion.',
    type: 'Descriptive',
    difficulty: 'Medium',
    marks: 5,
    topic: 'Mechanics',
  },
  {
    id: 'q-003',
    text: 'Calculate the escape velocity of Earth.',
    type: 'Numerical',
    difficulty: 'Hard',
    marks: 3,
    topic: 'Gravitation',
  },
];
