import React from 'react';
import { PageHeader } from '@/shared/components/layout/page-header';
import { ExportDialog } from '../components/ExportDialog';
import { Button } from '@/shared/components/ui/button';
import { Download, History, Database } from 'lucide-react';

export function ExportAuditLogsPage() {
  return (
    <div className="space-y-6 max-w-4xl">
      <PageHeader 
        title="Export Audit Data" 
        description="Generate downloadable reports of system activity for compliance and offline review." 
      />
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-8">
         <div className="border border-indigo-100 bg-indigo-50/50 rounded-xl p-8 flex flex-col items-center justify-center text-center">
            <div className="w-16 h-16 bg-indigo-100 text-indigo-600 rounded-full flex items-center justify-center mb-4">
               <Download className="w-8 h-8" />
            </div>
            <h3 className="font-bold text-lg text-slate-900 mb-2">New Export Request</h3>
            <p className="text-sm text-slate-600 mb-6">Generate a CSV, Excel, or PDF report based on specific date ranges, modules, and severity levels.</p>
            <ExportDialog 
               trigger={
                 <Button size="lg" className="bg-indigo-600 hover:bg-indigo-700 text-white w-full">
                    Configure Export
                 </Button>
               }
            />
         </div>

         <div className="space-y-4">
            <div className="p-6 bg-white border border-slate-200 rounded-xl">
               <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-2">
                     <History className="w-5 h-5 text-slate-400" />
                     <h4 className="font-bold text-slate-900">Recent Exports</h4>
                  </div>
               </div>
               
               <div className="space-y-3">
                  <div className="flex items-center justify-between p-3 bg-slate-50 rounded-lg border border-slate-100">
                     <div>
                        <p className="text-sm font-medium text-slate-900">Security_Audit_Oct_2026.pdf</p>
                        <p className="text-xs text-slate-500 mt-0.5">Generated by Admin • Today, 10:30 AM</p>
                     </div>
                     <Button variant="ghost" size="sm" className="text-indigo-600">Download</Button>
                  </div>
                  <div className="flex items-center justify-between p-3 bg-slate-50 rounded-lg border border-slate-100">
                     <div>
                        <p className="text-sm font-medium text-slate-900">API_Logs_Q3.csv</p>
                        <p className="text-xs text-slate-500 mt-0.5">Generated by System • Yesterday, 08:00 PM</p>
                     </div>
                     <Button variant="ghost" size="sm" className="text-indigo-600">Download</Button>
                  </div>
               </div>
            </div>

            <div className="p-6 bg-white border border-slate-200 rounded-xl">
               <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2">
                     <Database className="w-5 h-5 text-slate-400" />
                     <h4 className="font-bold text-slate-900">Data Retention Policy</h4>
                  </div>
               </div>
               <p className="text-sm text-slate-600">
                  Audit logs are retained in active storage for <span className="font-bold text-slate-900">90 days</span>. 
                  Older logs are archived and can be retrieved via support request.
               </p>
            </div>
         </div>
      </div>
    </div>
  );
}
